name: Build and deploy Todo App

on:
  pull_request:
    branches:
      - feat/practice-todo-app
  push:
    branches:
      - stag

jobs:
  test:
    name: Run tests on backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Load environment variables
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
      - name: Build and run tests
        uses: docker/build-push-action@v6
        with:
          target: test
          load: true

  push_docker_image:
    name: Build and push Docker image
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Load environment variables
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          target: final
          tags: ${{ secrets.DOCKER_USERNAME }}/nodejs-todo-app:latest
          build-args: |
            MYSQL_HOST=${{ secrets.DOCKER_COMPOSE_MYSQL_HOST }}
            MYSQL_USER=${{ secrets.DOCKER_COMPOSE_MYSQL_USER }}
            MYSQL_PASSWORD=${{ secrets.DOCKER_COMPOSE_MYSQL_PASSWORD }}
            MYSQL_DB=${{ secrets.DOCKER_COMPOSE_MYSQL_DB }}

  deploy:
    name: Deploy to Render Cloud
    if: github.ref == 'refs/heads/stag'
    needs: push-docker-image
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Render
        uses: JorgeLNJunior/render-deploy@v1.4.5
        with:
          service_id: ${{ secrets.RENDER_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}
