name: Build and deploy Todo App
on:
  pull_request:
    branches:
      - feat/practice-todo-app
  push:
    branches:
      - stag
jobs:
  test:
    name: Run tests on backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and run tests
        uses: docker/build-push-action@v6
        with:
          target: test
          load: true

  build:
    name: Build and push Docker image
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          target: final
          tags: ${{ secrets.DOCKER_USERNAME }}/nodejs-todo-app:latest
  deploy:
    name: Deploy to Render
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Render
        uses: JorgeLNJunior/render-deploy@v1.4.5
        with:
          service_id: ${{ secrets.RENDER_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}
